services:
  backend:
    build: ./backend
    container_name: ainki-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: ainki-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_PROXY_TARGET=http://backend:8000
    depends_on:
      - backend
