from typing import Optional
from .pg_connection import get_connection


CREATE_TABLE_CHUNKS = """
CREATE TABLE IF NOT EXISTS public.chunks (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id    integer NOT NULL,
    "date"    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content   text NOT NULL,
    "active?" boolean NOT NULL DEFAULT true,
    order_idx integer NOT NULL,
    page_idx  integer NOT NULL,
    reader    text NOT NULL DEFAULT 'PDFReader'
);
"""


CREATE_TABLE_DOCS_METADATA = """
CREATE TABLE IF NOT EXISTS public.docs_metadata (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    size_mb  numeric(12,6) DEFAULT 0.0,
    "date"   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name     text NOT NULL,
    folder   text
);
"""


CREATE_TABLE_USERS = """
CREATE TABLE IF NOT EXISTS public.users (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL,
    gmail      text NOT NULL,
    password   text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


def ensure_tables_exist() -> None:
    conn = get_connection()
    try:
        with conn.cursor() as cursor:
            cursor.execute(CREATE_TABLE_CHUNKS)
            cursor.execute(CREATE_TABLE_DOCS_METADATA)
            cursor.execute(CREATE_TABLE_USERS)
        conn.commit()
    finally:
        conn.close()


if __name__ == "__main__":
    ensure_tables_exist()